### ISSUE TITLE
Adding a function to the bot so he ignores you

### ISSUE THREAD

**Issue by NoobMage** [RedSparr0w/Discord-bot-pokeclicker#10]
So the bot reacts to keywords or phrases like "how to get" and sometime interferes with the conversation people had. so adding an option in form of a command maybe to let the bot know he can ignore you would be great.

**Comment by RedSparr0w** [comment]
Closed via 4d05cb86fee6b037e6946838a9fb8f2c8bc060d7

Won't tell members that joined the server more than a week ago about the faq/bot-commands/wiki.
