### ISSUE TITLE
[SUGGESTION] Change the link used for bot-coins reward tooltips

### ISSUE THREAD

**Issue by PixLSteam** [RedSparr0w/Discord-bot-pokeclicker#27]
Currently, it tries to open https://cancel which shows an ugly popup when you click the user's name. I propose changing this link to something more sensible, like a link to the answer given by that person.

**Comment by RedSparr0w** [comment]
Yeah that could work, wonder if it shows a pop up still, or just automatically goes to their answer 🤔 

Will give it a go later today

**Comment by RedSparr0w** [comment]
Should be implemented now 👍
