### ISSUE TITLE
Suggestion: auto-delete any message with the Shiny / Farm easter egg code

### ISSUE THREAD

**Issue by dragonkin550** [RedSparr0w/Discord-bot-pokeclicker#33]
With the recent explosion in new players and attention, the shiny and farm easter egg codes get shared on the discord a bunch, and have to be removed by mods or told to delete the message by other people in the server.  A feature to auto-delete any message containing those two codes would be welcome.

**Comment by RedSparr0w** [comment]
👍 Implemented with Discords auto-mod rules
