### ISSUE TITLE
[SUGGESTION] Consolidate /claim and /timely rewards

### ISSUE THREAD

**Issue by Blajuly** [RedSparr0w/Discord-bot-pokeclicker#38]
As it is right now, it shows the base reward, streak bonus, and role bonus separately. It'd be nice if, under that, there was a total reward displayed underneath it.

![image](https://user-images.githubusercontent.com/123192195/213754172-0db633b2-69e5-4cab-bddf-ded122347478.png)

**Comment by RedSparr0w** [comment]
Done 👍 
Thanks for the suggestion
